### PR TITLE
Chrome extension support

### PR DESCRIPTION
**Pull request by IAP-Reloaded**
You can now install this as an unpackaged extension by downloading the .ZIP.

I'd need contributor access to upload the .crx to releases.

### CODE REVIEW

**Comment by vyznev** [comment]
It's half past midnight here, and I was just going to sleep. :) But I'll take a look at this tomorrow. Thanks!

**Comment by IAP-Reloaded** [comment]
Sorry about that.

**Comment by vyznev** [comment]
No problem, I am still awake after all. :) Ps. Quick comment after glancing at the code: the SOUP injector is supposed to run at document-start; if you defer it to onload, some fixes will break (and CSS fixes may appear only with a delay). Is there some specific reason why you needed to defer the loading? (Also, I'm not sure if I like the footer notice. SOUP is supposed to be inconspicuous, and there's already a notice in the JS console if you need to check that it's working. Also, I suspect it may cause problems in chat.)

**Comment by IAP-Reloaded** [comment]
Apparently the hints don't work for Chrome extensions.

Also, you said that you were going to split up the fixes. I can do that
right now and also keep a combined one for scripts. How would it be
divided?

**Comment by vyznev** [comment]
I'm not totally sure, that's one reason why I haven't done it yet. :) I was thinking either lots of files with one fix per file, or just a couple of files with, say, one file per README section. What I really want to do is move away from the `fixes` array and stringifying JS functions, and instead have something like lots of little "soup scripts" with Greasemonkey-style metadata that get compiled into the actual user script / extension (and probably minified in the process). But that obviously requires writing the "compiler" script and developing an actual build process; the Perl script I currently have for extracting the metadata section is just a quick hack.

**Comment by vyznev** [comment]
Thanks a lot for taking the time to help me with this. I went and [added a manifest.json to the development branch](https://github.com/vyznev/soup/commit/29eb233875a8833cb35c6bf074c275fdc4b3676d) (not actually using your code directly, but certainly inspired by it), and it seems to be working. If you can give it some more testing, that'd be great! (I've also uploaded a draft package into Google Web Store, but for some reason it doesn't like my credit card so I can't pay the registration fee. :( Might be something to do with the fact that it expires next month.)

**Comment by vyznev** [comment]
With SOUP v1.46 now available as a Chrome and Firefox extension, I think this can be closed.

**Pull request closed without merging**
